// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = 5,
                            Breed = "Tortie",
                            Color = "Brown and Black",
                            Name = "Jackie",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 2,
                            Age = 11,
                            Breed = "Labrador",
                            Color = "Yellow",
                            Name = "Spike",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 3,
                            Age = 3,
                            Breed = "Tuxedo",
                            Color = "Black and White",
                            Name = "Felix",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 4,
                            Age = 24,
                            Breed = "Schnauzer",
                            Color = "White",
                            Name = "Poppins",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 5,
                            Age = 12,
                            Breed = "Bulldog",
                            Color = "Brown and White",
                            Name = "Benny",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
